### ISSUE TITLE
Git Ignored package.json

### ISSUE THREAD

**Issue by kalenjohnson** [artemsheludko/adam-blog#1]
Hey there, I really like the looks of your theme, very clean and minimal. However I'm curious since you have a gulp file, why `package.json` is git ignored. Generally that's something good to have if you have any Node dependencies, which there are obviously a couple from looking at `gulpfile.js`. Might be something to consider adding to the repo so others can just `npm install`.

**Comment by artemsheludko** [comment]
You're right. Added `gulpfile.js`. Thank you!
