### ISSUE TITLE
Page scroll issues

### ISSUE THREAD

**Issue by rahidelvi** [artemsheludko/adam-blog#5]
Hi Artem,

A [Chrome extension][1] I'm using seems to be conflicting with the scrolling behaviour on the adam-blog. I thought it could have been the `overflow: hidden` property, but that doesn't seem to be it. If I disable the extension I'm able to scroll on pages just fine.

Would you by chance know what code might be affecting the site's page scroll behaviour?

Thanks for sharing your work.

[1]: https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb

**Comment by artemsheludko** [comment]
@rahidelvi 
Hi, to be honest, I don't know. But the problem is precisely in the expansion Chrome because the extension does not work correctly and with other sites.

**Comment by rahidelvi** [comment]
@artemsheludko I was hoping to just comment out the code that was affecting the scroll behaviour, to see if that made a difference. I've never had a problem scrolling on websites with that extension before.

It's probably better to close out this issue for now.
