### ISSUE TITLE
Mobile Incompatibility

### ISSUE THREAD

**Issue by bedibyte** [artemsheludko/adam-blog#9]
I am using this theme for my blog about computer vision. So, there are a lot of code blocks being used at my site. It works really well on the laptop, but when i try to open my post on my phone, it loads only half way through and get stuck there.

Try opening this page up on your phone and you'll understand what i'm saying - https://bedibyte.github.io/blog/blob-tracking/

A solution to fix it would help me a lot (I'm loving the simplicity of the theme design, so i'm hoping that i do not have to switch to another theme). Thanks.

**Comment by artemsheludko** [comment]
@bedibyte Hi, If you want to remove the scroll along the x axis. Find the tag `pre` in the `main.css` file and add a few lines of code to it. I attach a screenshot of your problem.

![screen shot 2018-04-03 at 9 44 08 pm](https://user-images.githubusercontent.com/22279513/38269479-4d6ab56a-3789-11e8-841d-5c5d09a0c6c7.png)

**Comment by bedibyte** [comment]
That fixed it. Thanks a lot! @artemsheludko
